#!/usr/bin/env python3
"""Post-process GPU sweep (results/raw.jsonl):
   - bignum-recheck every escape/fuelout sample (Python ints, no overflow window)
   - validate inventories against literature + Lean-provable structure
   - emit CollatzCerts.lean (machine-verified cycle + range certificates)
   - emit results/summary.md tables
"""
import json, math, sys

RAW = "results/raw.jsonl"
rows = [json.loads(l) for l in open(RAW)]
byac = {(r["a"], r["c"]): r for r in rows}

def odd_step(n, a, c):
    m = a*n + c
    h = (m & -m).bit_length() - 1
    return m >> h

def classify_big(s, a, c, mins, cap_steps=2_000_000, cap_val=10**60):
    """Exact bignum orbit: returns ('cycle', min) or ('huge', peak) or ('undecided',)."""
    n = s
    ms = set(mins)
    for _ in range(cap_steps):
        if n in ms:
            return ("cycle", n)
        if n > cap_val:
            return ("huge", n)
        n = odd_step(n, a, c)
    return ("undecided",)

# ---- 1. bignum recheck of all sampled escapes/fuelouts ----
print("== bignum recheck of sampled escape/fuel-out starts ==")
problems = 0
for r in rows:
    a, c = r["a"], r["c"]
    mins = [cy["min"] for cy in r["cycles"]]
    for s in r["passB"]["samples"]:
        verdict = classify_big(s, a, c, mins)
        if a <= 3:
            # negative drift family: every sampled escapee must reconverge
            if verdict[0] != "cycle":
                print(f"  PROBLEM a={a} c={c} n={s}: {verdict}")
                problems += 1
            else:
                print(f"  a={a} c={c} n={s}: reconverges to cycle(min={verdict[1]}) after u64-window exit")
assert problems == 0, "a<=3 escapee failed to reconverge!"

# ---- 2. literature / structure validation ----
mins_of = lambda a, c: sorted(cy["min"] for cy in byac[(a, c)]["cycles"])
assert mins_of(3, 1) == [1], mins_of(3, 1)
assert mins_of(3, -1) == [1, 5, 17], mins_of(3, -1)            # 3x-1 (= Collatz on negatives)
assert mins_of(5, 1) == [1, 13, 17], mins_of(5, 1)             # known 5x+1 cycles
assert mins_of(7, 1) == [1], mins_of(7, 1)                     # universal cycle, a=2^3-1
assert set(mins_of(3, 5)) >= {1, 5, 19, 23}, mins_of(3, 5)     # Belaga-Mignotte 3x+5
# universal trivial cycle theorem (a = 2^k - 1): c itself is a cycle minimum... (c is min of its cycle
# when c small; at least c must lie ON some cycle => its cycle's min <= c and orbit of c returns)
for a in (3, 7, 15):
    for (aa, c) in byac:
        if aa != a or c < 1: continue
        st = classify_big(c, a, c, mins_of(a, c))
        assert st[0] == "cycle", (a, c, st)
# scaling conjugacy: c ≡ 0 (mod 3), a ≡ 0 or a ≡ 3 (mod 3) => orbit absorbed in 3Z, exact 3x rescale
assert mins_of(3, 3) == [3]
assert mins_of(3, 9) == [3*m for m in mins_of(3, 3)]
assert mins_of(3, 15) == [3*m for m in mins_of(3, 5)]
assert mins_of(9, 3) == [3*m for m in mins_of(9, 1)]           # both empty or scaled
assert mins_of(15, 3) == [3*m for m in mins_of(15, 1)]
print("== all literature/structure asserts passed ==")

# ---- 3. drift table ----
def drift_row(r):
    a, c = r["a"], r["c"]
    o, h = r["passB"]["oddsteps"], r["passB"]["halvings"]
    hpo = h / o if o else float("nan")
    return hpo, math.log(a) - hpo*math.log(2), math.log(a) - 2*math.log(2)

# ---- 4. emit CollatzCerts.lean ----
HDR = """/-
  CollatzCerts.lean — GENERATED by analyze.py from CUDA sweep results.
  Certificates:
    (i)  every discovered cycle is a genuine cycle       (kernel `decide`)
    (ii) for each variant, EVERY n in [1, 100000] either reaches the
         cycle inventory or exceeds the u64 window tau    (`native_decide`)
  Check with:  lean CollatzCerts.lean    (Lean 4.31.0)
-/

-- long cycles unfold ~10 elaborator frames per step; default depth 512 fails at len ≥ ~40
set_option maxRecDepth 100000

def T (a c n : Nat) : Nat := if n % 2 = 1 then a * n + c else n / 2

/-- 3x-1 variant (the one negative-c system in the sweep). -/
def Tm1 (n : Nat) : Nat := if n % 2 = 1 then 3 * n - 1 else n / 2

def iterN (f : Nat → Nat) : Nat → Nat → Nat
  | 0,     x => x
  | k + 1, x => iterN f k (f x)

/-- Does the orbit of n hit `mins` (or leave the window tau) within `fuel` steps? -/
def orbHits (f : Nat → Nat) (mins : List Nat) (tau : Nat) : Nat → Nat → Bool
  | _, 0     => false
  | n, k + 1 =>
    if mins.contains n then true
    else if tau < n then true
    else orbHits f mins tau (f n) k

/-- Check every start in [1, i+left) ... driver: checkFrom f mins tau fuel 1 N. -/
def checkFrom (f : Nat → Nat) (mins : List Nat) (tau fuel : Nat) : Nat → Nat → Bool
  | _, 0        => true
  | i, left + 1 =>
    if orbHits f mins tau i fuel then checkFrom f mins tau fuel (i + 1) left
    else false
"""

LEAN_N = 100_000
LEAN_FUEL = 200_000

def lname(a, c):
    return f"a{a}_c{'m1' if c == -1 else c}"

certs = [HDR]
for r in rows:
    a, c = r["a"], r["c"]
    fexpr = "Tm1" if c == -1 else f"(T {a} {c})"
    tau = r["tau"]
    mins = [cy["min"] for cy in r["cycles"]]
    certs.append(f"\n-- ==== variant a={a}, c={c} ====")
    for cy in r["cycles"]:
        tac = "decide" if cy["len"] <= 512 else "native_decide"
        certs.append(
            f"theorem cyc_{lname(a,c)}_m{cy['min']} : "
            f"iterN {fexpr} {cy['len']} {cy['min']} = {cy['min']} := by {tac}")
    ml = "[" + ", ".join(str(m) for m in mins) + "]"
    certs.append(
        f"theorem range_{lname(a,c)} : "
        f"checkFrom {fexpr} {ml} {tau} {LEAN_FUEL} 1 {LEAN_N} = true := by native_decide")

certs.append("\n#print axioms range_a3_c1")
certs.append("#print axioms cyc_a3_c1_m1")
open("CollatzCerts.lean", "w").write("\n".join(certs) + "\n")
print(f"== wrote CollatzCerts.lean: {sum(len(r['cycles']) for r in rows)} cycle certs + {len(rows)} range certs ==")

# ---- 5. summary tables ----
out = ["| a | c | N swept | cycles (odd minima) | converged % | escaped-window % | E[halv/odd step] | drift/odd step (meas) | drift (pred ln a - 2 ln 2) |",
       "|---|---|---------|--------------------|-------------|------------------|------------------|----------------------|-----------------------------|"]
for r in rows:
    a, c = r["a"], r["c"]
    nodd = r["N"] // 2
    conv = sum(r["passB"]["counts"])
    esc = r["passB"]["escape"]
    hpo, dm, dp = drift_row(r)
    minstr = ",".join(str(cy["min"]) for cy in r["cycles"]) or "(none)"
    if len(minstr) > 40: minstr = minstr[:37] + "..."
    out.append(f"| {a} | {c} | 2^{int(math.log2(r['N']))} | {len(r['cycles'])}: {minstr} | "
               f"{100*conv/nodd:.4f} | {100*esc/nodd:.4f} | {hpo:.4f} | {dm:+.4f} | {dp:+.4f} |")
open("results/summary.md", "w").write("\n".join(out) + "\n")
print("== wrote results/summary.md ==")

# ---- 6. cycle-equation identity: n0*(2^H - a^k) = c*W, W = sum a^(k-1-i) 2^(s_i) ----
print("== cycle-equation identity check ==")
for r in rows:
    a, c = r["a"], r["c"]
    for cy in r["cycles"]:
        n0 = cy["min"]; hs = []; n = n0
        while True:
            m = a*n + c
            h = (m & -m).bit_length() - 1
            hs.append(h); n = m >> h
            if n == n0: break
        k, H = len(hs), sum(hs)
        assert (k, H) == (cy["k"], cy["H"]), (a, c, n0, k, H, cy)  # GPU vs python cross-check
        W = sum(a**(k-1-i) * 2**sum(hs[:i]) for i in range(k))
        assert n0*(2**H - a**k) == c*W, (a, c, n0)
        cy["D"] = 2**H - a**k   # denominator, for the report
print("   all cycles satisfy n0*(2^H - a^k) = c*W (exact bignum) ==")

# drift sanity: H/k = log2(a) + (log2 n_start - log2 n_end)/k_mean, tends to 2 for a=3
# only in the long-orbit limit; allow the finite-orbit boundary term.
for (a, c) in [(3, 1), (3, -1)]:
    hpo, _, _ = drift_row(byac[(a, c)])
    assert abs(hpo - 2.0) < 0.05, (a, c, hpo)
print("== drift sanity (halvings/odd-step ≈ 2 up to boundary term) passed ==")
