/-
  CollatzCerts.lean — GENERATED by analyze.py from CUDA sweep results.
  Certificates:
    (i)  every discovered cycle is a genuine cycle       (kernel `decide`)
    (ii) for each variant, EVERY n in [1, 100000] either reaches the
         cycle inventory or exceeds the u64 window tau    (`native_decide`)
  Check with:  lean CollatzCerts.lean    (Lean 4.31.0)
-/

-- long cycles unfold ~10 elaborator frames per step; default depth 512 fails at len ≥ ~40
set_option maxRecDepth 100000

def T (a c n : Nat) : Nat := if n % 2 = 1 then a * n + c else n / 2

/-- 3x-1 variant (the one negative-c system in the sweep). -/
def Tm1 (n : Nat) : Nat := if n % 2 = 1 then 3 * n - 1 else n / 2

def iterN (f : Nat → Nat) : Nat → Nat → Nat
  | 0,     x => x
  | k + 1, x => iterN f k (f x)

/-- Does the orbit of n hit `mins` (or leave the window tau) within `fuel` steps? -/
def orbHits (f : Nat → Nat) (mins : List Nat) (tau : Nat) : Nat → Nat → Bool
  | _, 0     => false
  | n, k + 1 =>
    if mins.contains n then true
    else if tau < n then true
    else orbHits f mins tau (f n) k

/-- Check every start in [1, i+left) ... driver: checkFrom f mins tau fuel 1 N. -/
def checkFrom (f : Nat → Nat) (mins : List Nat) (tau fuel : Nat) : Nat → Nat → Bool
  | _, 0        => true
  | i, left + 1 =>
    if orbHits f mins tau i fuel then checkFrom f mins tau fuel (i + 1) left
    else false


-- ==== variant a=1, c=1 ====
theorem cyc_a1_c1_m1 : iterN (T 1 1) 2 1 = 1 := by decide
theorem range_a1_c1 : checkFrom (T 1 1) [1] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=-1 ====
theorem cyc_a3_cm1_m1 : iterN Tm1 2 1 = 1 := by decide
theorem cyc_a3_cm1_m5 : iterN Tm1 5 5 = 5 := by decide
theorem cyc_a3_cm1_m17 : iterN Tm1 18 17 = 17 := by decide
theorem range_a3_cm1 : checkFrom Tm1 [1, 5, 17] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=1 ====
theorem cyc_a3_c1_m1 : iterN (T 3 1) 3 1 = 1 := by decide
theorem range_a3_c1 : checkFrom (T 3 1) [1] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=3 ====
theorem cyc_a3_c3_m3 : iterN (T 3 3) 3 3 = 3 := by decide
theorem range_a3_c3 : checkFrom (T 3 3) [3] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=5 ====
theorem cyc_a3_c5_m1 : iterN (T 3 5) 4 1 = 1 := by decide
theorem cyc_a3_c5_m5 : iterN (T 3 5) 3 5 = 5 := by decide
theorem cyc_a3_c5_m19 : iterN (T 3 5) 8 19 = 19 := by decide
theorem cyc_a3_c5_m23 : iterN (T 3 5) 8 23 = 23 := by decide
theorem cyc_a3_c5_m187 : iterN (T 3 5) 44 187 = 187 := by decide
theorem cyc_a3_c5_m347 : iterN (T 3 5) 44 347 = 347 := by decide
theorem range_a3_c5 : checkFrom (T 3 5) [1, 5, 19, 23, 187, 347] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=7 ====
theorem cyc_a3_c7_m5 : iterN (T 3 7) 6 5 = 5 := by decide
theorem cyc_a3_c7_m7 : iterN (T 3 7) 3 7 = 7 := by decide
theorem range_a3_c7 : checkFrom (T 3 7) [5, 7] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=9 ====
theorem cyc_a3_c9_m9 : iterN (T 3 9) 3 9 = 9 := by decide
theorem range_a3_c9 : checkFrom (T 3 9) [9] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=11 ====
theorem cyc_a3_c11_m1 : iterN (T 3 11) 8 1 = 1 := by decide
theorem cyc_a3_c11_m11 : iterN (T 3 11) 3 11 = 11 := by decide
theorem cyc_a3_c11_m13 : iterN (T 3 11) 22 13 = 13 := by decide
theorem range_a3_c11 : checkFrom (T 3 11) [1, 11, 13] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=13 ====
theorem cyc_a3_c13_m1 : iterN (T 3 13) 5 1 = 1 := by decide
theorem cyc_a3_c13_m13 : iterN (T 3 13) 3 13 = 13 := by decide
theorem cyc_a3_c13_m131 : iterN (T 3 13) 39 131 = 131 := by decide
theorem cyc_a3_c13_m211 : iterN (T 3 13) 13 211 = 211 := by decide
theorem cyc_a3_c13_m227 : iterN (T 3 13) 13 227 = 227 := by decide
theorem cyc_a3_c13_m251 : iterN (T 3 13) 13 251 = 251 := by decide
theorem cyc_a3_c13_m259 : iterN (T 3 13) 13 259 = 259 := by decide
theorem cyc_a3_c13_m283 : iterN (T 3 13) 13 283 = 283 := by decide
theorem cyc_a3_c13_m287 : iterN (T 3 13) 13 287 = 287 := by decide
theorem cyc_a3_c13_m319 : iterN (T 3 13) 13 319 = 319 := by decide
theorem range_a3_c13 : checkFrom (T 3 13) [1, 13, 131, 211, 227, 251, 259, 283, 287, 319] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=15 ====
theorem cyc_a3_c15_m3 : iterN (T 3 15) 4 3 = 3 := by decide
theorem cyc_a3_c15_m15 : iterN (T 3 15) 3 15 = 15 := by decide
theorem cyc_a3_c15_m57 : iterN (T 3 15) 8 57 = 57 := by decide
theorem cyc_a3_c15_m69 : iterN (T 3 15) 8 69 = 69 := by decide
theorem cyc_a3_c15_m561 : iterN (T 3 15) 44 561 = 561 := by decide
theorem cyc_a3_c15_m1041 : iterN (T 3 15) 44 1041 = 1041 := by decide
theorem range_a3_c15 : checkFrom (T 3 15) [3, 15, 57, 69, 561, 1041] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=17 ====
theorem cyc_a3_c17_m1 : iterN (T 3 17) 9 1 = 1 := by decide
theorem cyc_a3_c17_m17 : iterN (T 3 17) 3 17 = 17 := by decide
theorem cyc_a3_c17_m23 : iterN (T 3 17) 49 23 = 23 := by decide
theorem range_a3_c17 : checkFrom (T 3 17) [1, 17, 23] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=3, c=19 ====
theorem cyc_a3_c19_m5 : iterN (T 3 19) 16 5 = 5 := by decide
theorem cyc_a3_c19_m19 : iterN (T 3 19) 3 19 = 19 := by decide
theorem range_a3_c19 : checkFrom (T 3 19) [5, 19] 4611686018427387904 200000 1 100000 = true := by native_decide

-- ==== variant a=5, c=1 ====
theorem cyc_a5_c1_m1 : iterN (T 5 1) 7 1 = 1 := by decide
theorem cyc_a5_c1_m13 : iterN (T 5 1) 10 13 = 13 := by decide
theorem cyc_a5_c1_m17 : iterN (T 5 1) 10 17 = 17 := by decide
theorem range_a5_c1 : checkFrom (T 5 1) [1, 13, 17] 3689348814741910118 200000 1 100000 = true := by native_decide

-- ==== variant a=5, c=3 ====
theorem cyc_a5_c3_m1 : iterN (T 5 3) 4 1 = 1 := by decide
theorem cyc_a5_c3_m3 : iterN (T 5 3) 7 3 = 3 := by decide
theorem cyc_a5_c3_m39 : iterN (T 5 3) 10 39 = 39 := by decide
theorem cyc_a5_c3_m43 : iterN (T 5 3) 10 43 = 43 := by decide
theorem cyc_a5_c3_m51 : iterN (T 5 3) 10 51 = 51 := by decide
theorem cyc_a5_c3_m53 : iterN (T 5 3) 10 53 = 53 := by decide
theorem cyc_a5_c3_m61 : iterN (T 5 3) 10 61 = 61 := by decide
theorem range_a5_c3 : checkFrom (T 5 3) [1, 3, 39, 43, 51, 53, 61] 3689348814741910118 200000 1 100000 = true := by native_decide

-- ==== variant a=5, c=5 ====
theorem cyc_a5_c5_m5 : iterN (T 5 5) 7 5 = 5 := by decide
theorem cyc_a5_c5_m65 : iterN (T 5 5) 10 65 = 65 := by decide
theorem cyc_a5_c5_m85 : iterN (T 5 5) 10 85 = 85 := by decide
theorem range_a5_c5 : checkFrom (T 5 5) [5, 65, 85] 3689348814741910118 200000 1 100000 = true := by native_decide

-- ==== variant a=5, c=7 ====
theorem cyc_a5_c7_m1 : iterN (T 5 7) 49 1 = 1 := by decide
theorem cyc_a5_c7_m7 : iterN (T 5 7) 7 7 = 7 := by decide
theorem cyc_a5_c7_m9 : iterN (T 5 7) 7 9 = 9 := by decide
theorem cyc_a5_c7_m57 : iterN (T 5 7) 60 57 = 57 := by decide
theorem cyc_a5_c7_m91 : iterN (T 5 7) 10 91 = 91 := by decide
theorem cyc_a5_c7_m119 : iterN (T 5 7) 10 119 = 119 := by decide
theorem range_a5_c7 : checkFrom (T 5 7) [1, 7, 9, 57, 91, 119] 3689348814741910118 200000 1 100000 = true := by native_decide

-- ==== variant a=5, c=9 ====
theorem cyc_a5_c9_m1 : iterN (T 5 9) 12 1 = 1 := by decide
theorem cyc_a5_c9_m3 : iterN (T 5 9) 4 3 = 3 := by decide
theorem cyc_a5_c9_m9 : iterN (T 5 9) 7 9 = 9 := by decide
theorem cyc_a5_c9_m29 : iterN (T 5 9) 90 29 = 29 := by decide
theorem cyc_a5_c9_m89 : iterN (T 5 9) 30 89 = 89 := by decide
theorem cyc_a5_c9_m117 : iterN (T 5 9) 10 117 = 117 := by decide
theorem cyc_a5_c9_m129 : iterN (T 5 9) 10 129 = 129 := by decide
theorem cyc_a5_c9_m153 : iterN (T 5 9) 10 153 = 153 := by decide
theorem cyc_a5_c9_m159 : iterN (T 5 9) 10 159 = 159 := by decide
theorem cyc_a5_c9_m183 : iterN (T 5 9) 10 183 = 183 := by decide
theorem range_a5_c9 : checkFrom (T 5 9) [1, 3, 9, 29, 89, 117, 129, 153, 159, 183] 3689348814741910118 200000 1 100000 = true := by native_decide

-- ==== variant a=5, c=11 ====
theorem cyc_a5_c11_m1 : iterN (T 5 11) 5 1 = 1 := by decide
theorem cyc_a5_c11_m11 : iterN (T 5 11) 7 11 = 11 := by decide
theorem cyc_a5_c11_m141 : iterN (T 5 11) 20 141 = 141 := by decide
theorem cyc_a5_c11_m143 : iterN (T 5 11) 10 143 = 143 := by decide
theorem cyc_a5_c11_m187 : iterN (T 5 11) 10 187 = 187 := by decide
theorem range_a5_c11 : checkFrom (T 5 11) [1, 11, 141, 143, 187] 3689348814741910118 200000 1 100000 = true := by native_decide

-- ==== variant a=7, c=1 ====
theorem cyc_a7_c1_m1 : iterN (T 7 1) 4 1 = 1 := by decide
theorem range_a7_c1 : checkFrom (T 7 1) [1] 2635249153387078655 200000 1 100000 = true := by native_decide

-- ==== variant a=7, c=3 ====
theorem cyc_a7_c3_m3 : iterN (T 7 3) 4 3 = 3 := by decide
theorem range_a7_c3 : checkFrom (T 7 3) [3] 2635249153387078655 200000 1 100000 = true := by native_decide

-- ==== variant a=7, c=5 ====
theorem cyc_a7_c5_m3 : iterN (T 7 5) 8 3 = 3 := by decide
theorem cyc_a7_c5_m5 : iterN (T 7 5) 4 5 = 5 := by decide
theorem cyc_a7_c5_m27 : iterN (T 7 5) 42 27 = 27 := by decide
theorem range_a7_c5 : checkFrom (T 7 5) [3, 5, 27] 2635249153387078655 200000 1 100000 = true := by native_decide

-- ==== variant a=7, c=7 ====
theorem cyc_a7_c7_m7 : iterN (T 7 7) 4 7 = 7 := by decide
theorem range_a7_c7 : checkFrom (T 7 7) [7] 2635249153387078655 200000 1 100000 = true := by native_decide

-- ==== variant a=7, c=9 ====
theorem cyc_a7_c9_m1 : iterN (T 7 9) 5 1 = 1 := by decide
theorem cyc_a7_c9_m9 : iterN (T 7 9) 4 9 = 9 := by decide
theorem range_a7_c9 : checkFrom (T 7 9) [1, 9] 2635249153387078655 200000 1 100000 = true := by native_decide

-- ==== variant a=7, c=11 ====
theorem cyc_a7_c11_m11 : iterN (T 7 11) 4 11 = 11 := by decide
theorem cyc_a7_c11_m23 : iterN (T 7 11) 46 23 = 23 := by decide
theorem range_a7_c11 : checkFrom (T 7 11) [11, 23] 2635249153387078655 200000 1 100000 = true := by native_decide

-- ==== variant a=9, c=1 ====
theorem range_a9_c1 : checkFrom (T 9 1) [] 2049638230412172287 200000 1 100000 = true := by native_decide

-- ==== variant a=9, c=3 ====
theorem range_a9_c3 : checkFrom (T 9 3) [] 2049638230412172287 200000 1 100000 = true := by native_decide

-- ==== variant a=9, c=5 ====
theorem range_a9_c5 : checkFrom (T 9 5) [] 2049638230412172287 200000 1 100000 = true := by native_decide

-- ==== variant a=9, c=7 ====
theorem cyc_a9_c7_m1 : iterN (T 9 7) 5 1 = 1 := by decide
theorem range_a9_c7 : checkFrom (T 9 7) [1] 2049638230412172287 200000 1 100000 = true := by native_decide

-- ==== variant a=9, c=9 ====
theorem range_a9_c9 : checkFrom (T 9 9) [] 2049638230412172287 200000 1 100000 = true := by native_decide

-- ==== variant a=9, c=11 ====
theorem range_a9_c11 : checkFrom (T 9 11) [] 2049638230412172287 200000 1 100000 = true := by native_decide

-- ==== variant a=11, c=1 ====
theorem range_a11_c1 : checkFrom (T 11 1) [] 1676976733973595508 200000 1 100000 = true := by native_decide

-- ==== variant a=11, c=3 ====
theorem range_a11_c3 : checkFrom (T 11 3) [] 1676976733973595508 200000 1 100000 = true := by native_decide

-- ==== variant a=11, c=5 ====
theorem cyc_a11_c5_m1 : iterN (T 11 5) 5 1 = 1 := by decide
theorem range_a11_c5 : checkFrom (T 11 5) [1] 1676976733973595508 200000 1 100000 = true := by native_decide

-- ==== variant a=13, c=1 ====
theorem range_a13_c1 : checkFrom (T 13 1) [] 1418980313362273122 200000 1 100000 = true := by native_decide

-- ==== variant a=13, c=3 ====
theorem cyc_a13_c3_m1 : iterN (T 13 3) 5 1 = 1 := by decide
theorem range_a13_c3 : checkFrom (T 13 3) [1] 1418980313362273122 200000 1 100000 = true := by native_decide

-- ==== variant a=15, c=1 ====
theorem cyc_a15_c1_m1 : iterN (T 15 1) 5 1 = 1 := by decide
theorem range_a15_c1 : checkFrom (T 15 1) [1] 1229782938247303372 200000 1 100000 = true := by native_decide

-- ==== variant a=15, c=3 ====
theorem cyc_a15_c3_m3 : iterN (T 15 3) 5 3 = 3 := by decide
theorem range_a15_c3 : checkFrom (T 15 3) [3] 1229782938247303372 200000 1 100000 = true := by native_decide

-- ==== variant a=15, c=5 ====
theorem cyc_a15_c5_m5 : iterN (T 15 5) 5 5 = 5 := by decide
theorem range_a15_c5 : checkFrom (T 15 5) [5] 1229782938247303372 200000 1 100000 = true := by native_decide

#print axioms range_a3_c1
#print axioms cyc_a3_c1_m1
