/-
GENERATED by the Rust counterexample search; standard positive 3n+1 only.
Run: lean +leanprover/lean4:v4.31.0 CollatzSearchCertsRust.lean

Each row certifies an EXACT trajectory to 1 and its recorded metrics, with no
appeal to previously verified ranges. Nat is arbitrary precision. Metrics use
ordinary steps: odd n -> 3*n+1, even n -> n/2. All starts exceed 2^71.
The universal checker-soundness proof is kernel-only and has no axioms.
The finite batch and numeric summaries use native_decide / generated native axioms:
the compiler and native runtime are in their trusted computing base.
This finite dataset does not prove the Collatz conjecture.
-/
namespace CollatzSearch
set_option maxRecDepth 100000
set_option maxHeartbeats 0

def step (n : Nat) : Nat := if n % 2 = 1 then 3 * n + 1 else n / 2

def iterate : Nat → Nat → Nat
  | 0, n => n
  | k + 1, n => iterate k (step n)

structure State where
  value : Nat
  peak : Nat
  elapsed : Nat := 0
  firstDescent : Nat := 0
  firstOne : Nat := 0

def tick (start : Nat) (s : State) : State :=
  let value := step s.value
  let elapsed := s.elapsed + 1
  { value := value, peak := max s.peak value, elapsed := elapsed,
    firstDescent := if s.firstDescent = 0 ∧ value < start then elapsed else s.firstDescent,
    firstOne := if s.firstOne = 0 ∧ value = 1 then elapsed else s.firstOne }

def scan (start : Nat) : Nat → State → State
  | 0, s => s
  | k + 1, s => scan start k (tick start s)

structure Row where
  start : Nat
  steps : Nat
  peakBits : Nat
  firstDescent : Nat
  prescribedStandardSteps : Nat

def initial (n : Nat) : State := { value := n, peak := n }

def verifyRow (r : Row) : Bool :=
  let s := scan r.start r.steps (initial r.start)
  decide (2 ^ 71 < r.start ∧ s.value = 1 ∧ s.firstOne = r.steps ∧
    s.peak.log2 + 1 = r.peakBits ∧ s.firstDescent = r.firstDescent ∧
    r.prescribedStandardSteps < s.firstDescent)

theorem scan_value : ∀ (k start : Nat) (s : State),
    (scan start k s).value = iterate k s.value
  | 0, _, _ => rfl
  | k + 1, start, s => scan_value k start (tick start s)

/-- A successful checker result implies actual convergence for the stated map. -/
theorem verifyRow_sound (r : Row) (h : verifyRow r = true) :
    ∃ k, iterate k r.start = 1 := by
  have hv : (scan r.start r.steps (initial r.start)).value = 1 :=
    (of_decide_eq_true h).2.1
  exact ⟨r.steps, by simpa [scan_value, initial] using hv⟩

