//! Deterministic starts shared with the original Python search.
//!
//! Loop ordering and deduplication are part of the dataset format: if two
//! families produce the same integer, the first label retains ownership.

use std::collections::HashSet;

use num_bigint::BigUint;
use num_traits::One;
use sha3::{
    Shake256,
    digest::{ExtendableOutput, Update, XofReader},
};

use crate::{Seed, search::critical_residue};

const BITS: [usize; 13] = [
    72, 96, 128, 192, 256, 384, 512, 768, 1024, 1536, 2048, 3072, 4096,
];
const OFFSETS: [u32; 12] = [1, 3, 5, 7, 9, 15, 31, 63, 127, 255, 511, 1023];
const PREFIX_BITS: [usize; 8] = [72, 128, 256, 512, 1024, 2048, 4096, 8192];
const CRITICAL_BITS: [usize; 7] = [128, 256, 512, 1024, 2048, 4096, 8192];
const HIGH_PARTS: [u32; 8] = [1, 3, 5, 7, 11, 27, 31, 63];

pub const FAMILIES: [&str; 4] = [
    "power_offsets",
    "all_odd_prefix",
    "critical_parity_prefix",
    "hash_control",
];

#[derive(Default)]
struct SeedBuilder {
    rows: Vec<Seed>,
    seen: HashSet<BigUint>,
}

impl SeedBuilder {
    fn add(
        &mut self,
        family: &'static str,
        label: String,
        start: BigUint,
        lean_expression: String,
        prescribed_shortcut_steps: u64,
        prescribed_standard_steps: u64,
    ) {
        if self.seen.contains(&start) {
            return;
        }
        assert!(start > (BigUint::one() << 71usize));
        assert!(start.bit(0));
        self.seen.insert(start.clone());
        self.rows.push(Seed {
            family,
            label,
            start,
            lean_expression,
            prescribed_shortcut_steps,
            prescribed_standard_steps,
        });
    }
}

/// Return the exact ordered seed list generated by `search_counterexample.py`.
///
/// SHAKE input strings, digest lengths, byte order, bit masking, and first
/// ownership of duplicate starts match the Python implementation.
pub fn seeds() -> Vec<Seed> {
    let mut builder = SeedBuilder::default();

    for bits in BITS {
        let power = BigUint::one() << bits;
        for offset in OFFSETS {
            for positive in [false, true] {
                let (operator, start) = if positive {
                    ("+", &power + offset)
                } else {
                    ("-", &power - offset)
                };
                builder.add(
                    "power_offsets",
                    format!("2^{bits}{operator}{offset}"),
                    start,
                    format!("2 ^ {bits} {operator} {offset}"),
                    0,
                    0,
                );
            }
        }
    }

    for bits in PREFIX_BITS {
        let power = BigUint::one() << bits;
        for q in HIGH_PARTS {
            builder.add(
                "all_odd_prefix",
                format!("{q}*2^{bits}-1"),
                &power * q - BigUint::one(),
                format!("{q} * 2 ^ {bits} - 1"),
                bits as u64,
                2 * bits as u64,
            );
        }
    }

    for length in CRITICAL_BITS {
        let (residue, ones) = critical_residue(length);
        let power = BigUint::one() << length;
        for q in HIGH_PARTS {
            builder.add(
                "critical_parity_prefix",
                format!("critical({length})+{q}*2^{length}"),
                &residue + &power * q,
                format!("{residue} + {q} * 2 ^ {length}"),
                length as u64,
                length as u64 + ones,
            );
        }
    }

    for bits in BITS {
        let mask = (BigUint::one() << bits) - BigUint::one();
        for index in 0..64 {
            let tag = format!("collatz-counterexample-search-v1:{bits}:{index}");
            let mut hasher = Shake256::default();
            hasher.update(tag.as_bytes());
            let mut reader = hasher.finalize_xof();
            let mut bytes = vec![0u8; bits.div_ceil(8)];
            reader.read(&mut bytes);
            let mut start = BigUint::from_bytes_be(&bytes) & &mask;
            start.set_bit((bits - 1) as u64, true);
            start.set_bit(0, true);
            let expression = start.to_str_radix(10);
            builder.add(
                "hash_control",
                format!("shake256({bits},{index})"),
                start,
                expression,
                0,
                0,
            );
        }
    }

    builder.rows
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn complete_seed_list_matches_python_dataset() {
        let data: serde_json::Value =
            serde_json::from_str(include_str!("../results/counterexample_search.json"))
                .expect("the committed Python dataset must be valid JSON");
        let expected = data["rows"]
            .as_array()
            .expect("dataset rows must be an array");
        let generated = seeds();
        assert_eq!(expected.len(), 1257);
        assert_eq!(generated.len(), expected.len());

        for (index, (seed, row)) in generated.iter().zip(expected).enumerate() {
            let expected_seed = serde_json::json!({
                "family": row["family"],
                "label": row["label"],
                "start": row["start"],
                "lean_expression": row["lean_expression"],
                "prescribed_shortcut_steps": row["prescribed_shortcut_steps"],
                "prescribed_standard_steps": row["prescribed_standard_steps"],
            });
            let actual_seed = serde_json::json!({
                "family": seed.family,
                "label": seed.label,
                "start": seed.start.to_str_radix(10),
                "lean_expression": seed.lean_expression,
                "prescribed_shortcut_steps": seed.prescribed_shortcut_steps,
                "prescribed_standard_steps": seed.prescribed_standard_steps,
            });
            assert_eq!(actual_seed, expected_seed, "seed row {index} differs");
        }

        let mut family_order = Vec::new();
        for seed in &generated {
            if family_order.last().copied() != Some(seed.family) {
                family_order.push(seed.family);
            }
        }
        assert_eq!(family_order, FAMILIES);
    }
}
